#!/usr/bin/env python3
"""Interactive setup: asks for the interface language and API keys and writes .env.

Run once after cloning:  python3 configure.py
"""
from __future__ import annotations

import getpass
import sys
from pathlib import Path

ENV_PATH = Path(__file__).resolve().parent / ".env"

TEXT = {
    "en": {
        "exists": ".env already exists. Overwrite it? [y/N]: ",
        "kept": "Keeping the existing .env. Nothing changed.",
        "intervals_key": "Intervals.icu API key (Settings → Developer Settings): ",
        "athlete": "Intervals.icu athlete id, e.g. i123456 (from your profile URL): ",
        "anthropic": "Anthropic API key (console.anthropic.com → API Keys): ",
        "model": "Model [claude-sonnet-5]: ",
        "hidden": "(input is hidden)",
        "empty": "This value is required.",
        "bad_athlete": "The athlete id usually starts with “i”, e.g. i123456. Use it anyway? [y/N]: ",
        "done": "Saved {path}. Start the app with:  python3 app.py",
    },
    "ru": {
        "exists": "Файл .env уже есть. Перезаписать? [y/N]: ",
        "kept": "Оставляю существующий .env без изменений.",
        "intervals_key": "API-ключ Intervals.icu (Settings → Developer Settings): ",
        "athlete": "ID атлета в Intervals.icu, например i123456 (из адреса профиля): ",
        "anthropic": "API-ключ Anthropic (console.anthropic.com → API Keys): ",
        "model": "Модель [claude-sonnet-5]: ",
        "hidden": "(ввод не отображается)",
        "empty": "Это значение обязательно.",
        "bad_athlete": "ID атлета обычно начинается с «i», например i123456. Всё равно использовать? [y/N]: ",
        "done": "Сохранено в {path}. Запуск:  python3 app.py",
    },
}


def ask(prompt: str, secret: bool = False, default: str = "", required: bool = True, t: dict | None = None) -> str:
    while True:
        value = (getpass.getpass(prompt) if secret else input(prompt)).strip()
        if not value and default:
            return default
        if value or not required:
            return value
        print("  " + t["empty"])


def main() -> None:
    print("\nHome Trainer setup\n")
    lang = ""
    while lang not in ("en", "ru"):
        lang = input("Interface language / Язык интерфейса [en/ru]: ").strip().lower() or "en"
    t = TEXT[lang]

    if ENV_PATH.exists() and input(t["exists"]).strip().lower() not in ("y", "yes", "д", "да"):
        print(t["kept"])
        return

    intervals_key = ask(t["intervals_key"] + t["hidden"] + " ", secret=True, t=t)
    athlete = ask(t["athlete"], t=t)
    if not athlete.startswith("i") and input(t["bad_athlete"]).strip().lower() not in ("y", "yes", "д", "да"):
        athlete = ask(t["athlete"], t=t)
    anthropic_key = ask(t["anthropic"] + t["hidden"] + " ", secret=True, t=t)
    model = ask(t["model"], default="claude-sonnet-5", t=t)

    ENV_PATH.write_text(
        "# Generated by configure.py\n"
        f"LANGUAGE={lang}\n\n"
        f"INTERVALS_API_KEY={intervals_key}\n"
        f"INTERVALS_ATHLETE_ID={athlete}\n"
        f"ANTHROPIC_API_KEY={anthropic_key}\n\n"
        f"MODEL={model}\n"
        "SUMMARY_MODEL=claude-haiku-4-5-20251001\n\n"
        "HOST=127.0.0.1\n"
        "PORT=8765\n",
        encoding="utf-8",
    )
    try:
        ENV_PATH.chmod(0o600)  # ключи видны только владельцу файла
    except OSError:
        pass
    print("\n" + t["done"].format(path=ENV_PATH) + "\n")


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print()
        sys.exit(1)
